# Generated by Django 2.2.5 on 2019-09-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitute', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('street_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StreetCrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.CharField(max_length=200)),
                ('persistent_id', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('location_type', models.CharField(max_length=200)),
                ('location_subtype', models.CharField(max_length=200)),
                ('outcome_status', models.CharField(max_length=200)),
                ('outcome_category', models.CharField(max_length=200)),
                ('outcome_date', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_level_crimes.CrimeCategories')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_level_crimes.Location')),
            ],
        ),
    ]
